name: Passky
version: ${project.version}
main: com.rabbitcomapny.Passky
api-version: 1.13
authors: [RabbitCompany]
description: Fastest login plugin
commands:
  login:
    usage: /<command>
    aliases: [log, l]
    description: Login to your minecraft account
  register:
    usage: /<command>
    aliases: [reg, r]
    description: Register to your minecraft account
  changepassword:
    usage: /<command>
    aliases: [changepass, cp]
    description: Change password for your minecraft account