name: Passky
version: ${project.version}
main: com.rabbitcomapny.Passky
api-version: 1.13
authors: [RabbitCompany,sandtechnology]
description: Fastest login plugin
commands:
  login:
    usage: /<command>
    aliases: [ log, l ]
    description: Login to your minecraft account
  register:
    usage: /<command>
    aliases: [ reg, r ]
    description: Register to your minecraft account
  changepassword:
    usage: /<command>
    aliases: [ changepass, cp ]
    description: Change password for your minecraft account
  forcechangepassword:
    usage: /<command>
    aliases: [ forcechangepass,fcp, fp ]
    permission: passky.forcechangepassword
    description: Forced change password for an player minecraft account
  forceregister:
    usage: /<command>
    aliases: [ forceregister,fr ]
    permission: passky.forceregister
    description: Forced register for an player minecraft account
permissions:
  passky.forcechangepassword:
    default: op
    description: Allow to use forcechangepassword command
  passky.forceregister:
    default: op
    description: Allow to use forceregister command